// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsu8DdM_uCQ4Qpb6aVE9zQmk-T-jAb_SI',
    appId: '1:69776057506:web:7c6ce72f73e4bc30a2e3fb',
    messagingSenderId: '69776057506',
    projectId: 'skillshare-33883',
    authDomain: 'skillshare-33883.firebaseapp.com',
    storageBucket: 'skillshare-33883.appspot.com',
    measurementId: 'G-86E5W0KLT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFIXZmEeGOvhq6MqKiy6nIguaXAl1Opus',
    appId: '1:69776057506:android:1386e915e9a88e1ca2e3fb',
    messagingSenderId: '69776057506',
    projectId: 'skillshare-33883',
    storageBucket: 'skillshare-33883.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQRDaN5gnFilaouPTugKNnppcHMctaVL0',
    appId: '1:69776057506:ios:11e9f5ece300a776a2e3fb',
    messagingSenderId: '69776057506',
    projectId: 'skillshare-33883',
    storageBucket: 'skillshare-33883.appspot.com',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQRDaN5gnFilaouPTugKNnppcHMctaVL0',
    appId: '1:69776057506:ios:11e9f5ece300a776a2e3fb',
    messagingSenderId: '69776057506',
    projectId: 'skillshare-33883',
    storageBucket: 'skillshare-33883.appspot.com',
    iosBundleId: 'com.example.mobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsu8DdM_uCQ4Qpb6aVE9zQmk-T-jAb_SI',
    appId: '1:69776057506:web:6d674b75a3ac7b42a2e3fb',
    messagingSenderId: '69776057506',
    projectId: 'skillshare-33883',
    authDomain: 'skillshare-33883.firebaseapp.com',
    storageBucket: 'skillshare-33883.appspot.com',
    measurementId: 'G-4XVTNZXWV4',
  );
}
